### ISSUE TITLE
Additional resource

### ISSUE THREAD

**Issue by RachelScodes** [cyrusinnovation/just-not-sorry#11]
Please read this: http://nymag.com/thecut/2015/07/can-we-just-like-get-over-the-way-women-talk.html

**Comment by tami-cyrus** [comment]
Thank you for sharing. We are aware that everyone has the right to speak however they choose. Just Not Sorry empowers people who are choosing to change their patterns because they are seeing negative impacts to make better choices. We simply want people to be conscious of their tone so that if they want to change something that they can.

We're sorry if this offends you.

Tami Reiss
CEO
http://www.cyrusinnovation.com/
@tamireiss
212-647-7186
Agile reinforcement to accelerate your development
Best place in NYC for female founders to build great products

**Comment by RachelScodes** [comment]
Understood
