### ISSUE TITLE
Deleting extra characters while extension is enabled

### ISSUE THREAD

**Issue by sbenario** [cyrusinnovation/just-not-sorry#6]
Noticed this behavior which I assume is unintentional.

Repro steps:
1) Write some text in a new email in gmail. Hit return once or twice, type "thanks " on its own line
2) Hold CMD and press Delete (probably works on PC with ctrl-backspace)

Expected result: Delete the entire current line and leave cursor at the beginning of the current line (ie. cmd-delete does not change the line that the cursor is on.

Actual result: When the plugin is enabled, cmd-delete deletes the entire line and then moves the cursor up to the end of the previous text, blowing away any whitespace in between.

Disabling the plugin and refreshing the page fixes the issue.

**Comment by sbrudz** [comment]
This is definitely a bug.  It's been annoying me, too.  I haven't had a chance to fix it yet but I did some diagnosis work to pinpoint it.  Adding implementation notes below.

---

The problem is in the [Caret.js](https://github.com/ichord/Caret.js) library that is used to maintain the cursor position after the highlighting is applied.  The getPos function creates a selection from the start to the cursor position, converts that to a string, and then returns the length of that string to get the position of the cursor.  The string conversion strips out any line breaks, so the number of characters passed to the setPos function is wrong in cases with whitespace.

One possible fix could be to rewrite the getPos function so that it walks the nodes of the DOM instead of doing a string conversion.

FYI, JustNotSorry is currently using my [fork](https://github.com/sbrudz/Caret.js) of Caret.js that enables use of the setPos function with ContentEditable form fields.
